language: java
script:
- "./gradlew build"
deploy:
  api_key:
    secure: XsKYjqwWUM9ieOYheehWg74wquwuRW3yS3v2kG2PEBN8oYJrfZ3gXVhZOaBJkv0dwFpX7PX6f5dTNGQl+a5AilHo3UX2DIHgJcCVjcJQt81xFX1Bz/Q5X5NK8GnZMQe/Gm0pwGbtG1PX1POI6xrdHqLBwI00piLTB0J9p5Y+lzEBoXfvGMMj+XQAfpWF5dGJwAxnkCTL8UfKb4HLYByAMvOUFbgNrmnRjuqE55OzSzJfPj6BWHa5BaIqNLw/PzCoAwDAIB5w0bMGE5v2Q+k8RVK32xCh7jICoyB5dKNk2gmkxpA7G8BS/wHN/2/Zb0fOLxBIvyEXLOEPyZJqoJEbRCNK+rqm6XMEhAtBcyj3l3VCJMrSofjZ6aGYwGjkkKAMU/J+k9rM674P3uELPfw6pcuQ6Ut97Qak8dWVY+j544/hfO3DH5MmJIElAhoQLw9KbWwnjkOzx81UfaRV8HSImcWDPskROJlgdY+GDhX13vIUntF4bs3Q9MUG0arvfdgxZneU1ASgn1F0GsFqIsn/b8wxDEM6t0VXVTNXpghyn492I3D71ml1hkmDsSbG+RjzQC5MJto19iVcPS7UisOEjOKa1hPlz5VwHSFy/QvcJdA+iD0UaDG1n7Rz0D5gHvLAWkXJVhNe9eRET3VWXuRUlH7j4VC26RQPNuammDcA5vw=
  app: groupup-backend
  on: main

