language: java
script:
- "./gradlew build"
deploy:
  provider: heroku
  api_key:
    secure: xms6Q+iQejJUKRMqs6yE1XxJEiYjYwwTG/E2hgyrZtdrBZ1zTleDM+q66oqMjGeaXRYyKQxmPq3BC5ZS/mfbL0qjv2KYnvdrLccAgW8LgccxU6+kSyenhFWMMqNZKtb/pbFJ6DxWawhc9tdR8XcatB1U6WKwnU4fp2o8baRSTvr8WCbOGaKwORjM3XcbPHiQoaw8xFjpjM5P8Ndb0nQ5y2/jLjQAS8p6ekRR5vIlic3VxPHxUVkbHEnJKYL1kaE9PsuAFMozbNMp3KV2TGG1T0CwxS03nfpY4eqzRx6L4M5TvCc2j2Bqw8EUwR855J2CJxhv0zHMmX2w5e7iveVuXZAZrdrQcZ54sQnflhkHq5A4TjNTiYnaLHYC9p5+8KHfrVxNTb44CYHKjkN9xPKbaPmsdESiaArwplP7NfvLLAYEJkznVrDOOWfUybMPVhj9kqqmF9tpkmpoMdXFH3hbk277huqG+wBENbyEnCJfKtSmsGci+Ffgf44a0CM3MYbiK7RHJOi0IzLYEAOJtARww3sNEeiFIurQzdgV1B+2V6doG2147JFHmPAB6nOBi8BwwrdZHyNybA77MteYysOSuBYGaKPeaGzjmL5UnTWSgm3nZzxbTVV7YIoYunqsiPaxUT5/fASvKfLjIUr46h4xyzIKzr2C7Nz6/s4ASxkWE48=
  app: groupup-backend
  on: main
